# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."step-ca" = {
    image = "smallstep/step-ca:latest";
    volumes = [
      "/root/container_data/step-ca:/home/step:rw"
    ];
    ports = [
      "8500:8500/tcp"
    ];
    dependsOn = [
      "step-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=step-ca"
      "--network=infra-tls_default"
    ];
  };
  systemd.services."podman-step-ca" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-infra-tls_default.service"
    ];
    requires = [
      "podman-network-infra-tls_default.service"
    ];
    partOf = [
      "podman-compose-infra-tls-root.target"
    ];
    wantedBy = [
      "podman-compose-infra-tls-root.target"
    ];
  };
  virtualisation.oci-containers.containers."step-db" = {
    image = "mariadb:latest";
    environment = {
      "MYSQL_DATABASE" = "stepca";
      "MYSQL_PASSWORD" = "123passqwe";
      "MYSQL_ROOT_PASSWORD" = "123passqwe";
      "MYSQL_USER" = "step";
    };
    volumes = [
      "/root/container_data/step-db:/var/lib/mysql:rw"
    ];
    ports = [
      "3306:3306/tcp"
    ];
    user = "1000:1000";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=step-db"
      "--network=infra-tls_default"
    ];
  };
  systemd.services."podman-step-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-infra-tls_default.service"
    ];
    requires = [
      "podman-network-infra-tls_default.service"
    ];
    partOf = [
      "podman-compose-infra-tls-root.target"
    ];
    wantedBy = [
      "podman-compose-infra-tls-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-infra-tls_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f infra-tls_default";
    };
    script = ''
      podman network inspect infra-tls_default || podman network create infra-tls_default
    '';
    partOf = [ "podman-compose-infra-tls-root.target" ];
    wantedBy = [ "podman-compose-infra-tls-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-infra-tls-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
